### ISSUE TITLE
Option to not show the output when activated

### ISSUE THREAD

**Issue by mkargus** [rojo-rbx/vscode-rojo#15]
The extension currently shows the output every time it is activated.

![0eccc7c0-df73-4d47-a78a-703a7391b9d8](https://user-images.githubusercontent.com/14226603/63229589-06072280-c1d0-11e9-8720-08746489895b.gif)

Line to edit:
https://github.com/rojo-rbx/vscode-rojo/blob/449d7fe406ac178ce3f1195049d81fb654eecad8/src/Rojo.ts#L116

**Comment by evaera** [comment]
Sometimes Rojo will give you diagnostic error messages in that panel if there's something wrong with your configuration. I usually just close it after I click start and see that it works. 

If possible I think I'd rather just change it to detect the success case and show a notification instead of the output channel, but show it in case of error.
